#:schema node_modules/wrangler/config-schema.json
name = "logalise-db"
main = "src/main.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "logalise-db"
database_id = "c0ee9a66-926d-4f35-af97-63346d2885a6"
